---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  containers:
    - image: netshoot
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
      name: netshoot
  restartPolicy: Always
