apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  externalUrl: "http://prom.k-space.ee/"
  replicas: 1
  shards: 1
  serviceAccountName: prometheus
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
 #  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
#  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
#  probeNamespaceSelector: {}
  probeSelector: {}
#  ruleNamespaceSelector: {}
  ruleSelector: {}
  retentionSize: 800MiB
  resources:
    limits:
      cpu: 500m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 200Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: prometheus